services:
  ws4kp:
    image: ghcr.io/netbymatt/ws4kp:latest
    container_name: ws4kp
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - settings.env
      - messages.env
    volumes:
      - ./music:/usr/share/nginx/html/music


  ws4channels:
    image: ghcr.io/rice9797/ws4channels:latest
    container_name: ws4channels
    restart: unless-stopped
    depends_on:
      - ws4kp
    ports:
      - "9798:9798"
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ./music:/app/music
    environment:
      - ZIP_CODE=${ZIP_CODE}
      - WS4KP_HOST=ws4kp
      - WS4KP_PORT=8080
      - VIDEO_OPTIONS=-c:v h264_qsv -b:v 1000k


  xteve:
    image: dnsforge/xteve:latest
    container_name: xteve
    restart: unless-stopped
    network_mode: host
    volumes:
      - /opt/xteve/config:/home/xteve/conf
      - /opt/xteve/tmp:/tmp/xteve
    environment:
      TZ: America/Chicago
